### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by ClintonYounge** [ClintonYounge/Catalog-Of-Things-Ruby-Capstone#42]
Link to repo- https://github.com/ClintonYounge/Catalog-Of-Things-Ruby-Capstone/projects/1

NB: There are 3 members in this group.

Team member 1- @sylvester-wamaya 
Team member 2- @mpa-mxiang 
Team member 3- @ClintonYounge

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @ClintonYounge, @mpa-mxiang, and @sylvester-wamaya👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [x] Some of the task cards are missing the description, Please make sure all tasks cards have descriptions as requested in the project requirements.
Example: 
![image](https://github.com/ClintonYounge/Catalog-Of-Things-Ruby-Capstone/assets/83803414/8bef000b-b621-45a3-974d-29065156c178)

- [ ] Some of the task cards are missing point prefixes, Please make sure all task cards have point prefixes as requested in the project requirements.
Example:
![image](https://github.com/ClintonYounge/Catalog-Of-Things-Ruby-Capstone/assets/83803414/b2ebf017-e059-4948-9db6-ff504cc98447)

- [x] Below task card is missing an assigned team member, Please make sure to assign a team member to it as requested in the project requirements.
![image](https://github.com/ClintonYounge/Catalog-Of-Things-Ruby-Capstone/assets/83803414/1dcdb176-2992-4064-846a-61c63fcf2642)

- [ ] Please make sure time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks. Currently, I can see the points are not equal, some team members have way more points than others.




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- All tasks added ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- [x] I noticed that team member 2 has 13 hours of tasks while team member 1 has 8 hours, which is quite not fair, I will encourage you to distribute it fairly.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danmainah** [comment]
Hi @ClintonYounge, @mpa-mxiang, and @sylvester-wamaya, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️Implemented the change requested to ensure tasks are distributed fairly among all team members.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mpa-mxiang** [comment]
Thank you @danmainah  for the approval!
